name          'garethr-kibana'
version       '0.2.0'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Kibana logstash interface'
project_page  'https://github.com/garethr/garethr-kibana'
dependency    'puppetlabs/vcsrepo'
dependency    'puppetlabs/git'
dependency    'puppetlabs/ruby'
dependency    'puppetlabs/stdlib'
dependency    'ploperations/bundler'
