name          'garethr-kibana'
version       '0.0.3'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Kibana logstash interface'
project_page  'https://github.com/garethr/garethr-kibana'
dependency    'maestrodev/wget'
